{% set name = "turn_by_turn" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/turn_by_turn-{{ version }}.tar.gz
  sha256: 3b7faff693b199d918b741a9653d93c775c9a15d0617028b4b026ca698597dcf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - numpy >=1.24
    - scipy >=1.5
    - pandas >=2.1
    - python >=3.7
    - sdds >=0.4
    - h5py >=2.9

test:
  imports:
    - turn_by_turn
    - turn_by_turn.io
    - turn_by_turn.structures
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pylhc/turn_by_turn
  summary: Read and write turn-by-turn measurement files from different particle accelerator formats.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Python package to read and write BPM measurement files from different particle accelerators.
  doc_url: https://pylhc.github.io/turn_by_turn/

extra:
  recipe-maintainers:
    - fsoubelet
